### ISSUE TITLE
Bundled GNURadio + GrOsmoSDR (PortAudio version)

### ISSUE THREAD

**Issue by veso266** [pothosware/pothos#52] opened 2015-12-22 19:38 UTC
Hi I've installed pothos again and I've set C:\Program Files (x86)\gnuradio\etc\gnuradio\conf.d\gr-audio.conf and changed from auto to portaudio: 

[code]
# This file contains system wide configuration data for GNU Radio.
# You may override any setting on a per-user basis by editing
# ~/.gnuradio/config.conf

# specify which audio module to load, or use "auto" to have the system
# select one.  Valid choices depend on your OS and which modules
# you've installed, but typically include:
# auto, alsa, oss, portaudio, jack, osx, windows

[audio]

audio_module = portaudio
[/code]

but it still wan't to use Audio source arch: windows but I know I've setted the right config?
see here: 
![gnuradioportaudio](https://cloud.githubusercontent.com/assets/6347325/11936849/da47f8d6-a810-11e5-8f39-8cf76f2ac6d9.png)

PS: I have some problems with UDP Source/sink it always trows this error: 
![udp](https://cloud.githubusercontent.com/assets/6347325/11938052/2d4d1f28-a818-11e5-8b8c-cb36c5f76ef9.png)

Thanks for Anwsering and Best Regards

**Comment by guruofquality** [comment] 2016-01-10 19:22
Duplicate of: https://github.com/pothosware/PothosSDR/issues/11

**Closed by guruofquality** 2016-01-10 19:22 UTC
Labels: duplicate
